// Central name-generator blacklist.
// Any word listed here (compared lower-case) is force-excluded from every generated name,
// across every breed, trait and gender pool. Add new words to the relevant section.
export const BANNED_WORDS = new Set<string>([
  // -- "-by" suffix names (111) --------------------------------------------
  "ambleby", "bannerby", "bedraggleby", "bellowby", "blazeby", "blurby", "bobbleby", "boltby",
  "bonusby", "braveby", "brightby", "brushby", "bulletby", "cannonby", "champby", "charmby",
  "cherishby", "cleverby", "confettiby", "cottonby", "countessby", "dappleby", "dashby", "dazzleby",
  "dearby", "diamondby", "doodleby", "drifterby", "duchessby", "dusterby", "earnestby", "eleganceby",
  "faithfulby", "fanby", "featherby", "flagby", "flashby", "floofby", "flourishby", "galaxyby",
  "gemby", "gentleby", "glowby", "goldstarby", "graceby", "heroby", "honourby", "huntby",
  "hurtleby", "jewelby", "ladyby", "legendby", "lightningby", "loyalby", "marbleby", "mosaicby",
  "mucksby", "muddleby", "nobleby", "pearlby", "pennantby", "pepperby", "plumeby", "preciousby",
  "princessby", "prizeby", "queenby", "ragtagby", "rewardby", "rhythmby", "roanby", "rocketby",
  "rumpleby", "scroungeby", "shineby", "slumberby", "smartby", "snowdriftby", "spatterby", "speckleby",
  "spinby", "spottyby", "sprinkleby", "sprintby", "starby", "starmapby", "starryby", "steadby",
  "streamby", "swayby", "sweepby", "sweetby", "swishby", "tangleby", "tattersby", "torpedoby",
  "trailby", "treasureby", "treatby", "trueby", "tuftyby", "turboby", "twizzleby", "vagabondby",
  "waifby", "warpby", "waverby", "welldoneby", "whirlyby", "whizzby", "zipby",
  // -- "-ton" / "-ford" suffix names (158) ---------------------------------
  "ambleston", "bannerton", "bassetford", "bayford", "bayton", "bedraggleton", "bellford", "bellton",
  "blazeford", "blazeton", "blobton", "blotton", "blurton", "boingford", "boltford", "braveton",
  "brindleton", "buntington", "championford", "charmford", "cherishton", "cleverton", "cloudton", "confettiford",
  "dashford", "dashton", "dazzleton", "detectington", "dishevelton", "doodleton", "dotford", "dozington",
  "droopington", "earneston", "faithfulton", "fanford", "featherford", "featherton", "flagford", "flashford",
  "flashton", "fleckton", "flopearton", "floppington", "flourishford", "fluffington", "freckleton", "frillford",
  "frizzleton", "fullpelton", "gentleton", "glowton", "graceford", "graceton", "grimton", "grubton",
  "grungeford", "gutterton", "honourton", "huntford", "hurtleton", "inkton", "jewelton", "jowlton",
  "ladyford", "ladyton", "legford", "leggington", "longearton", "loyalton", "marbleford", "marbleton",
  "marshmallowton", "matton", "meringueford", "mosaicton", "mottleford", "muckton", "muzzleton", "nimbleford",
  "nimbleton", "nobleston", "nobleton", "noodleford", "noodleton", "noseton", "patchworkton", "piebaldton",
  "plumeford", "plumeton", "pompleton", "poodlington", "preciouston", "prizeford", "quarryford", "queenford",
  "queenton", "quickton", "ragamuffinton", "ramshackleton", "rascalton", "rocketton", "ruffton", "rumpleford",
  "scoutford", "scrubbleton", "shagford", "shaggleton", "shineton", "sleepyton", "sleuthford", "smarton",
  "snivelton", "snoutford", "speckleston", "speckleton", "spinford", "spinton", "splotchton", "spotford",
  "sprinkleford", "sprintford", "starryford", "steadton", "streakford", "streakton", "streamford", "stripeton",
  "swayford", "swayton", "sweetford", "sweeton", "swirlford", "swishford", "swishton", "swooshton",
  "tailford", "tracerton", "treasureton", "trueton", "tuffleton", "twizzleford", "unkempton", "vroomton",
  "waifton", "wanderton", "warpton", "waverton", "wavyford", "welldonton", "whirlyton", "whizzton",
  "wisperton", "wispford", "wobbleton", "woolford", "wrinkleton", "zoomford",
]);
